//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class InvoiceDetail : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, e);
            }
        }

        public string InvoiceID { get; set; }
        public string ProductID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> UnitPrice { get; set; }

        private Nullable<double> _amount;
        public Nullable<double> Amount
        {
            get
            {
                return _amount;
            }
            set
            {
                _amount = value;
                OnPropertyChanged(new PropertyChangedEventArgs("Amount"));
            }
        }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
