//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payslip
    {
        public string ID { get; set; }
        public string EmployeeID { get; set; }
        public string ProductID { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Pay { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
